services:
  qubic-http:
    image: ghcr.io/qubic/qubic-http:v0.8.0
    container_name: qubic-http
    environment:
      QUBIC_API_SIDECAR_SERVER_HTTP_HOST: "0.0.0.0:8000"
      QUBIC_API_SIDECAR_SERVER_GRPC_HOST: "0.0.0.0:8001"
      QUBIC_API_SIDECAR_POOL_NODE_FETCHER_URL: "http://qubic-nodes:8080/status"
      QUBIC_API_SIDECAR_POOL_NODE_FETCHER_TIMEOUT: "20s"
    networks:
      - archiver
    depends_on:
      qubic-nodes:
        condition: service_healthy
    restart: always

  qubic-archiver:
    image: ghcr.io/qubic/qubic-archiver:v0.11.1
    container_name: qubic-archiver
    ports:
      - "127.0.0.1:8001:8000"
    environment:
      QUBIC_ARCHIVER_SERVER_HTTP_HOST: "0.0.0.0:8000"
      QUBIC_ARCHIVER_SERVER_GRPC_HOST: "0.0.0.0:8001"
      QUBIC_ARCHIVER_SERVER_CHAIN_TICK_FETCH_URL: "http://qubic-nodes:8080/max-tick"
      QUBIC_ARCHIVER_POOL_NODE_FETCHER_URL: "http://qubic-nodes:8080/status"
      QUBIC_ARCHIVER_QUBIC_PROCESS_TICK_TIMEOUT: "20s"
      QUBIC_ARCHIVER_QUBIC_DISABLE_TRANSACTION_STATUS_ADDON: "false"
    volumes:
      - ./store/archiver:/app/store
    networks:
      - archiver
    depends_on:
      qubic-nodes:
        condition: service_healthy
    restart: always

  qubic-nodes:
    image: ghcr.io/qubic/qubic-nodes:v2.1.0
    container_name: qubic-nodes
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      QUBIC_NODES_QUBIC_PEER_LIST: "1.2.3.4;2.3.4.5"
    volumes:
      - ./store/qubic-nodes:/app/store
    networks:
      - archiver
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/status"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

networks:
  archiver: